### ISSUE TITLE
Avatar 1000 Not Found

### ISSUE THREAD

**Issue by Nictheboy** [SageSeekerSociety/cheese-backend#81]
Every time running test, although tests can pass, ```ERROR [ExceptionsHandler] Avatar 1000 Not Found``` is logged:

```
[Nest] 3666  - 03/11/2024, 9:20:33 AM   ERROR [ExceptionsHandler] Avatar 1000 Not Found
AvatarNotFoundError: Avatar 1000 Not Found
    at AvatarsService.getAvatarPath (/home/runner/work/cheese-backend/cheese-backend/src/avatars/avatars.service.ts:64:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at AvatarsController.getAvatar (/home/runner/work/cheese-backend/cheese-backend/src/avatars/avatars.controller.ts:42:24)
    at /home/runner/work/cheese-backend/cheese-backend/node_modules/.pnpm/@nestjs+core@10.3.1_@nestjs+common@10.3.1_@nestjs+platform-express@10.3.1_reflect-metadata@0.1.14_rxjs@7.8.1/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at /home/runner/work/cheese-backend/cheese-backend/node_modules/.pnpm/@nestjs+core@10.3.1_@nestjs+common@10.3.1_@nestjs+platform-express@10.3.1_reflect-metadata@0.1.14_rxjs@7.8.1/node_modules/@nestjs/core/router/router-proxy.js:9:17
```
![Screenshot_2024-03-11_21-26-16](https://github.com/SageSeekerSociety/cheese-backend/assets/61396218/873fde2a-4482-444a-87b1-5c7205336348)

**Comment by corporal9736** [comment]
This seems to be expected?
![Screenshot_20240318_034629](https://github.com/SageSeekerSociety/cheese-backend/assets/60935688/59ca8f99-ab76-4f43-96f8-648672f9fb5a)

**Comment by nameisyui** [comment]
I forgot to add BaseErrorExceptionFilter......
